import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist_Mono } from "next/font/google";
import "./globals.css";

const weddingSans = localFont({
  variable: "--font-geist-sans",
  display: "swap",
  src: [
    {
      path: "./fonts/Itim-Regular.ttf",
      weight: "400",
      style: "normal",
    }
  ],
});



// const weddingSans = localFont({
//   variable: "--font-geist-sans",
//   display: "swap",
//   src: [
//     {
//       path: "./fonts/NotoSansThai-Regular.ttf",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "./fonts/NotoSansThai-Bold.ttf",
//       weight: "700",
//       style: "normal",
//     },
//   ],
// });

const leagueScript = localFont({
  variable: "--font-league-script",
  display: "swap",
  src: [
    {
      path: "./fonts/LeagueScript-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${weddingSans.variable} ${leagueScript.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
